// lib/product.ts

export interface Product {
    id: number;
    name: string;
    price: string;
    image: string;
    hoverImage: string;
    description?: string;
    category: "men" | "women" | "kids" | "hotpick";
    tabs?: string[];
    oldPrice?: string;
    discount?: string;
    sizes: string[];
    images?: string[];
    colorAvai: string[]; // valid CSS color names
}

export const products: Product[] = [
    // ===================== MEN =====================
    {
        id: 1,
        name: "Urban Slim Stretch Jeans - Black",
        price: "$48.00",
        oldPrice: "$72.00",
        discount: "35% OFF",
        image: "/mens/men1.avif",
        hoverImage: "/productImg/creamshirt.webp",
        description: "Slim fit stretch denim jeans designed for comfort and a modern look.",
        category: "men",
        tabs: ["streetwear"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["black", "navy", "gray", "olive"],
        images: ["/mens/men1.avif", "/mens/men2.avif", "/productImg/creamshirt.webp"],
    },
    {
        id: 2,
        name: "Everyday Cotton Overshirt",
        price: "$59.00",
        oldPrice: "$79.00",
        discount: "25% OFF",
        image: "https://k72.ca/uploads/teamMembers/Carl_480x640-480x640.jpg",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Soft-touch cotton overshirt with a relaxed fit for layering.",
        category: "men",
        tabs: ["weekday"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["beige", "olive", "tan", "brown"],
    },
    {
        id: 3,
        name: "Classic Crewneck Sweatshirt",
        price: "$39.00",
        oldPrice: "$49.00",
        discount: "20% OFF",
        image: "/productImg/sweatshirt.webp",
        hoverImage: "/mens/men2.avif",
        description: "Premium cotton sweatshirt with ribbed cuffs for everyday comfort.",
        category: "men",
        tabs: ["latest"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["beige", "olive", "navy", "white"],
    },
    {
        id: 4,
        name: "Tailored Wool Blend Coat",
        price: "$120.00",
        oldPrice: "$160.00",
        discount: "25% OFF",
        image: "https://k72.ca/uploads/teamMembers/Lawrence_480x640-480x640.jpg",
        hoverImage: "/mens/men3.avif",
        description: "Sophisticated overcoat crafted from a wool blend with clean lines.",
        category: "men",
        tabs: ["collection"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["charcoal", "camel", "brown", "black"],
    },
    {
        id: 5,
        name: "Relaxed Fit Linen Shirt",
        price: "$44.00",
        image: "/images/newin1.avif",
        hoverImage: "/productImg/creamshirt.webp",
        description: "Breathable linen shirt perfect for a relaxed summer day.",
        category: "men",
        tabs: ["latest"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["white", "skyblue", "lightgray", "tan"],
    },

    // ===================== WOMEN =====================
    {
        id: 11,
        name: "Cropped Denim Jacket",
        price: "$75.00",
        oldPrice: "$120.00",
        discount: "35% OFF",
        image: "/womens/womens.jpg",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Stylish cropped denim jacket with raw-edge hem.",
        category: "women",
        tabs: ["latest"],
        sizes: ["XS", "S", "M", "L"],
        colorAvai: ["blue", "white", "black", "gray"],
    },
    {
        id: 12,
        name: "Flowy Floral Midi Dress",
        price: "$89.00",
        oldPrice: "$110.00",
        discount: "19% OFF",
        image: "/mens/men1.avif",
        hoverImage: "/productImg/creamshirt.webp",
        description: "Romantic floral dress with a soft satin finish.",
        category: "women",
        tabs: ["collection"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["pink", "lavender", "cream", "peach"],
    },
    {
        id: 13,
        name: "Ribbed Knit Top",
        price: "$35.00",
        oldPrice: "$45.00",
        discount: "22% OFF",
        image: "/mens/men2.avif",
        hoverImage: "/mens/men3.avif",
        description: "Stretchy ribbed top with a flattering neckline.",
        category: "women",
        tabs: ["weekday"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["beige", "black", "white", "gray"],
    },
    {
        id: 14,
        name: "Pleated Wide-Leg Trousers",
        price: "$68.00",
        oldPrice: "$85.00",
        discount: "20% OFF",
        image: "https://k72.ca/uploads/teamMembers/Carl_480x640-480x640.jpg",
        hoverImage: "/productImg/sweatshirt.webp",
        description: "High-rise pleated trousers with elegant flow.",
        category: "women",
        tabs: ["streetwear"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["cream", "olive", "black", "navy"],
    },
    {
        id: 15,
        name: "Oversized Wool Cardigan",
        price: "$95.00",
        oldPrice: "$130.00",
        discount: "25% OFF",
        image: "/images/newin2.avif",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Chunky knit cardigan with an oversized silhouette.",
        category: "women",
        tabs: ["latest"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["beige", "brown", "gray", "white"],
    },

    // ======= 5 NEW WOMEN LATEST ITEMS =======
    {
        id: 201,
        name: "Wrap Front Midi Skirt",
        price: "$72.00",
        oldPrice: "$95.00",
        discount: "24% OFF",
        image: "/images/newin1.avif",
        hoverImage: "/images/newin3.avif",
        description: "Elegant wrap skirt with tie detail for a flattering fit.",
        category: "women",
        tabs: ["latest"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["beige", "black", "olive", "tan"],
    },
    {
        id: 202,
        name: "Lightweight Puff Sleeve Blouse",
        price: "$65.00",
        oldPrice: "$82.00",
        discount: "21% OFF",
        image: "/womens/womens.jpg",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Feminine puff-sleeve blouse perfect for any occasion.",
        category: "women",
        tabs: ["latest"],
        sizes: ["XS", "S", "M", "L"],
        colorAvai: ["white", "lightblue", "pink", "lavender"],
    },
    {
        id: 203,
        name: "High Neck Ribbed Dress",
        price: "$79.00",
        oldPrice: "$99.00",
        discount: "20% OFF",
        image: "/images/newin2.avif",
        hoverImage: "/images/newin3.avif",
        description: "Fitted ribbed dress with high neck for chic comfort.",
        category: "women",
        tabs: ["latest"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["black", "gray", "red", "beige"],
    },
    {
        id: 204,
        name: "Relaxed Fit Blazer",
        price: "$110.00",
        oldPrice: "$135.00",
        discount: "19% OFF",
        image: "/mens/men3.avif",
        hoverImage: "/productImg/creamshirt.webp",
        description: "Structured yet comfortable blazer for modern styling.",
        category: "women",
        tabs: ["latest"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["navy", "beige", "charcoal", "black"],
    },
    {
        id: 205,
        name: "Everyday Wide-Leg Jeans",
        price: "$88.00",
        oldPrice: "$112.00",
        discount: "21% OFF",
        image: "/images/newin3.avif",
        hoverImage: "/productImg/sweatshirt.webp",
        description: "Relaxed wide-leg denim jeans with premium wash.",
        category: "women",
        tabs: ["latest"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["lightblue", "blue", "black", "gray"],
    },

    // ===================== KIDS =====================
    {
        id: 21,
        name: "Kids Cotton Hoodie",
        price: "$29.00",
        oldPrice: "$38.00",
        discount: "24% OFF",
        image: "/productImg/sweatshirt.webp",
        hoverImage: "/mens/men2.avif",
        description: "Comfy everyday hoodie for school and playtime.",
        category: "kids",
        tabs: ["latest"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["blue", "red", "green", "yellow"],
    },
    {
        id: 22,
        name: "Printed Graphic Tee",
        price: "$19.00",
        image: "/mens/men1.avif",
        hoverImage: "/mens/men3.avif",
        description: "Bright graphic print t-shirt made from 100% cotton.",
        category: "kids",
        tabs: ["streetwear"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["white", "yellow", "orange", "blue"],
    },
    {
        id: 23,
        name: "Kids Denim Overalls",
        price: "$42.00",
        oldPrice: "$55.00",
        discount: "23% OFF",
        image: "/images/newin1.avif",
        hoverImage: "/productImg/creamshirt.webp",
        description: "Durable overalls with adjustable straps and roomy pockets.",
        category: "kids",
        tabs: ["collection"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["blue", "lightblue", "gray", "navy"],
    },
    {
        id: 24,
        name: "Soft Knit Sweater",
        price: "$38.00",
        image: "/images/newin2.avif",
        hoverImage: "/images/newin3.avif",
        description: "Warm and lightweight sweater for cozy days.",
        category: "kids",
        tabs: ["weekday"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["pink", "mintgreen", "white", "yellow"],
    },
    {
        id: 25,
        name: "Comfy Cotton Joggers",
        price: "$27.00",
        oldPrice: "$35.00",
        discount: "20% OFF",
        image: "https://k72.ca/uploads/teamMembers/Carl_480x640-480x640.jpg",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Stretchy joggers with soft fleece interior.",
        category: "kids",
        tabs: ["streetwear"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["gray", "navy", "blue", "black"],
    },
    {
        id: 101,
        name: "Basic Crewneck Tee",
        price: "$17.00",
        oldPrice: "$22.00",
        discount: "23% OFF",
        image: "/mens/men1.avif",
        hoverImage: "/mens/men2.avif",
        description: "Soft everyday cotton tee for comfort and play.",
        category: "hotpick",
        tabs: ["latest"],
        colorAvai: ["White", "Light Green"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 102,
        name: "Relaxed Denim Jacket",
        price: "$59.00",
        oldPrice: "$79.00",
        discount: "25% OFF",
        image: "/mens/men2.avif",
        hoverImage: "/mens/men3.avif",
        description: "Casual denim jacket with comfy fit.",
        category: "hotpick",
        tabs: ["best-seller"],
        colorAvai: ["Indigo", "Black"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 103,
        name: "Everyday Chino Shorts",
        price: "$29.00",
        oldPrice: "$39.00",
        discount: "26% OFF",
        image: "/mens/men1.avif",
        hoverImage: "/mens/men2.avif",
        description: "Lightweight chinos for warm days.",
        category: "hotpick",
        tabs: ["summer"],
        colorAvai: ["Khaki", "Navy"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 104,
        name: "Lightweight Hoodie",
        price: "$42.00",
        oldPrice: "$52.00",
        discount: "19% OFF",
        image: "/mens/men2.avif",
        hoverImage: "/mens/men3.avif",
        description: "Layer-friendly hoodie for everyday wear.",
        category: "hotpick",
        tabs: ["cozy"],
        colorAvai: ["Grey", "Olive"],
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 105,
        name: "Classic Slip-On Sneakers",
        price: "$45.00",
        oldPrice: "$60.00",
        discount: "25% OFF",
        image: "/mens/men1.avif",
        hoverImage: "/mens/men2.avif",
        description: "Easy slip-on sneakers with clean lines.",
        category: "hotpick",
        tabs: ["footwear"],
        colorAvai: ["White", "Black"],
        sizes: ["S", "M", "L", "XL"],
    },

];
