// lib/product.ts

export interface Product {
    id: number;
    name: string;
    price: string;
    image: string;
    hoverImage: string;
    description?: string;
    category: "men" | "women" | "kids";
    tabs?: string[];
    oldPrice?: string;
    discount?: string;
    sizes?: string[];
    images?: string[];
    colorAvai?: string[];
}

export const products: Product[] = [
    // ===================== MEN =====================
    {
        id: 1,
        name: "Urban Slim Stretch Jeans - Black",
        price: "$48.00",
        oldPrice: "$72.00",
        discount: "35% OFF",
        image: "/mens/men1.avif",
        hoverImage: "/productImg/creamshirt.webp",
        description: "Slim fit stretch denim jeans designed for comfort and a modern look.",
        category: "men",
        tabs: ["streetwear"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["Black", "Navy", "Grey"],
        images: ["/mens/men1.avif", "/mens/men1.avif", "/productImg/creamshirt.webp"],
    },
    {
        id: 2,
        name: "Everyday Cotton Overshirt",
        price: "$59.00",
        oldPrice: "$79.00",
        discount: "25% OFF",
        image: "https://k72.ca/uploads/teamMembers/Carl_480x640-480x640.jpg",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Soft-touch cotton overshirt with a relaxed fit for layering.",
        category: "men",
        tabs: ["weekday"],
        sizes: ["M", "L", "XL"],
        colorAvai: ["Beige", "Olive", "Stone"],
    },
    {
        id: 3,
        name: "Classic Crewneck Sweatshirt",
        price: "$39.00",
        oldPrice: "$49.00",
        discount: "20% OFF",
        image: "/productImg/sweatshirt.webp",
        hoverImage: "/mens/men2.avif",
        description: "Premium cotton sweatshirt with ribbed cuffs for everyday comfort.",
        category: "men",
        tabs: ["latest"],
        sizes: ["S", "M", "L"],
        colorAvai: ["Beige", "Olive", "Navy"],
    },
    {
        id: 4,
        name: "Tailored Wool Blend Coat",
        price: "$120.00",
        oldPrice: "$160.00",
        discount: "25% OFF",
        image: "https://k72.ca/uploads/teamMembers/Lawrence_480x640-480x640.jpg",
        hoverImage: "/mens/men3.avif",
        description: "Sophisticated overcoat crafted from a wool blend with clean lines.",
        category: "men",
        tabs: ["collection"],
        sizes: ["M", "L", "XL"],
        colorAvai: ["Charcoal", "Camel"],
    },
    {
        id: 5,
        name: "Relaxed Fit Linen Shirt",
        price: "$44.00",
        image: "/images/newin1.avif",
        hoverImage: "/productImg/creamshirt.webp",
        description: "Breathable linen shirt perfect for a relaxed summer day.",
        category: "men",
        tabs: ["latest"],
        sizes: ["S", "M", "L"],
        colorAvai: ["White", "Sky Blue"],
    },
    {
        id: 6,
        name: "Denim Jacket Vintage Wash",
        price: "$68.00",
        oldPrice: "$85.00",
        discount: "20% OFF",
        image: "/mens/men2.avif",
        hoverImage: "/mens/men1.avif",
        description: "Timeless denim jacket with authentic vintage-style wash.",
        category: "men",
        tabs: ["streetwear"],
        sizes: ["M", "L", "XL"],
        colorAvai: ["Blue", "Light Blue"],
    },
    {
        id: 7,
        name: "Athletic Fit Joggers",
        price: "$49.00",
        oldPrice: "$60.00",
        discount: "18% OFF",
        image: "https://k72.ca/uploads/teamMembers/Olivier_480x640-480x640.jpg",
        hoverImage: "/productImg/sweatshirt.webp",
        description: "Lightweight joggers designed for comfort and mobility.",
        category: "men",
        tabs: ["weekday"],
        colorAvai: ["Grey", "Navy"],
    },
    {
        id: 8,
        name: "Essential Cotton T-Shirt",
        price: "$22.00",
        oldPrice: "$30.00",
        discount: "27% OFF",
        image: "/mens/men2.avif",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Soft, breathable cotton t-shirt — a wardrobe essential.",
        category: "men",
        tabs: ["latest"],
        sizes: ["S", "M", "L", "XL"],
        colorAvai: ["White", "Black", "Grey"],
    },
    {
        id: 9,
        name: "Rugged Cargo Pants",
        price: "$55.00",
        oldPrice: "$70.00",
        discount: "21% OFF",
        image: "/mens/men3.avif",
        hoverImage: "/images/newin3.avif",
        description: "Utility cargo pants with multiple pockets and a durable finish.",
        category: "men",
        tabs: ["streetwear"],
        sizes: ["M", "L", "XL"],
        colorAvai: ["Olive", "Khaki", "Black"],
    },
    {
        id: 10,
        name: "Fleece Quarter-Zip Pullover",
        price: "$62.00",
        image: "/mens/men3.avif",
        hoverImage: "/productImg/sweatshirt.webp",
        description: "Warm fleece pullover with half-zip and contrast detail.",
        category: "men",
        tabs: ["collection"],
        colorAvai: ["Navy", "Forest Green"],
    },

    // ===================== WOMEN =====================
    {
        id: 11,
        name: "Cropped Denim Jacket",
        price: "$75.00",
        oldPrice: "$120.00",
        discount: "35% OFF",
        image: "/womens/womens.jpg",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Stylish cropped denim jacket with raw-edge hem.",
        category: "women",
        tabs: ["latest"],
        sizes: ["XS", "S", "M", "L"],
        colorAvai: ["Blue", "White"],
    },
    {
        id: 12,
        name: "Flowy Floral Midi Dress",
        price: "$89.00",
        oldPrice: "$110.00",
        discount: "19% OFF",
        image: "/mens/men1.avif",
        hoverImage: "/productImg/creamshirt.webp",
        description: "Romantic floral dress with a soft satin finish.",
        category: "women",
        tabs: ["collection"],
        sizes: ["S", "M", "L"],
        colorAvai: ["Pink", "Lavender"],
    },
    {
        id: 13,
        name: "Ribbed Knit Top",
        price: "$35.00",
        oldPrice: "$45.00",
        discount: "22% OFF",
        image: "/mens/men2.avif",
        hoverImage: "/mens/men3.avif",
        description: "Stretchy ribbed top with a flattering neckline.",
        category: "women",
        tabs: ["weekday"],
        colorAvai: ["Beige", "Black"],
    },
    {
        id: 14,
        name: "Pleated Wide-Leg Trousers",
        price: "$68.00",
        oldPrice: "$85.00",
        discount: "20% OFF",
        image: "https://k72.ca/uploads/teamMembers/Carl_480x640-480x640.jpg",
        hoverImage: "/productImg/sweatshirt.webp",
        description: "High-rise pleated trousers with elegant flow.",
        category: "women",
        tabs: ["streetwear"],
        sizes: ["S", "M", "L"],
        colorAvai: ["Cream", "Olive"],
    },
    {
        id: 15,
        name: "Oversized Wool Cardigan",
        price: "$95.00",
        oldPrice: "$130.00",
        discount: "25% OFF",
        image: "/images/newin2.avif",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Chunky knit cardigan with an oversized silhouette.",
        category: "women",
        tabs: ["latest"],
        sizes: ["S", "M", "L"],
        colorAvai: ["Beige", "Brown"],
    },
    {
        id: 16,
        name: "Satin Slip Dress",
        price: "$78.00",
        oldPrice: "$100.00",
        discount: "22% OFF",
        image: "/images/newin3.avif",
        hoverImage: "/mens/men1.avif",
        description: "Minimal satin dress for a smooth, luxe feel.",
        category: "women",
        tabs: ["collection"],
        sizes: ["XS", "S", "M"],
        colorAvai: ["Champagne", "Emerald"],
    },
    {
        id: 17,
        name: "Cropped Hoodie",
        price: "$49.00",
        oldPrice: "$59.00",
        discount: "17% OFF",
        image: "/productImg/sweatshirt.webp",
        hoverImage: "/mens/men2.avif",
        description: "Soft cropped hoodie for a sporty, laid-back vibe.",
        category: "women",
        tabs: ["streetwear"],
        sizes: ["XS", "S", "M"],
        colorAvai: ["Black", "Cream", "Lavender"],
    },
    {
        id: 18,
        name: "High-Waisted Jeans",
        price: "$55.00",
        image: "https://k72.ca/uploads/teamMembers/Olivier_480x640-480x640.jpg",
        hoverImage: "/productImg/creamshirt.webp",
        description: "Classic high-waisted jeans with straight legs.",
        category: "women",
        tabs: ["latest"],
        sizes: ["S", "M", "L"],
        colorAvai: ["Light Blue", "Indigo"],
    },
    {
        id: 19,
        name: "Linen Blend Blazer",
        price: "$89.00",
        oldPrice: "$105.00",
        discount: "15% OFF",
        image: "/mens/men3.avif",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Tailored linen blazer with a modern relaxed cut.",
        category: "women",
        tabs: ["weekday"],
        colorAvai: ["Beige", "Olive"],
    },
    {
        id: 20,
        name: "Everyday Basic Tee",
        price: "$24.00",
        image: "/mens/men1.avif",
        hoverImage: "/productImg/sweatshirt.webp",
        description: "Soft-touch cotton t-shirt in a cropped silhouette.",
        category: "women",
        tabs: ["latest"],
        colorAvai: ["White", "Grey"],
    },

    // ===================== KIDS =====================
    {
        id: 21,
        name: "Kids Cotton Hoodie",
        price: "$29.00",
        oldPrice: "$38.00",
        discount: "24% OFF",
        image: "/productImg/sweatshirt.webp",
        hoverImage: "/mens/men2.avif",
        description: "Comfy everyday hoodie for school and playtime.",
        category: "kids",
        tabs: ["latest"],
        sizes: ["S", "M", "L"],
        colorAvai: ["Blue", "Red"],
    },
    {
        id: 22,
        name: "Printed Graphic Tee",
        price: "$19.00",
        image: "/mens/men1.avif",
        hoverImage: "/mens/men3.avif",
        description: "Bright graphic print t-shirt made from 100% cotton.",
        category: "kids",
        tabs: ["streetwear"],
        colorAvai: ["White", "Yellow"],
    },
    {
        id: 23,
        name: "Kids Denim Overalls",
        price: "$42.00",
        oldPrice: "$55.00",
        discount: "23% OFF",
        image: "/images/newin1.avif",
        hoverImage: "/productImg/creamshirt.webp",
        description: "Durable overalls with adjustable straps and roomy pockets.",
        category: "kids",
        tabs: ["collection"],
        colorAvai: ["Blue", "Light Blue"],
    },
    {
        id: 24,
        name: "Soft Knit Sweater",
        price: "$38.00",
        image: "/images/newin2.avif",
        hoverImage: "/images/newin3.avif",
        description: "Warm and lightweight sweater for cozy days.",
        category: "kids",
        tabs: ["weekday"],
        colorAvai: ["Pink", "Mint Green"],
    },
    {
        id: 25,
        name: "Comfy Cotton Joggers",
        price: "$27.00",
        oldPrice: "$35.00",
        discount: "20% OFF",
        image: "https://k72.ca/uploads/teamMembers/Carl_480x640-480x640.jpg",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Stretchy joggers with soft fleece interior.",
        category: "kids",
        tabs: ["streetwear"],
        colorAvai: ["Grey", "Navy"],
    },
    {
        id: 26,
        name: "Kids Rain Jacket",
        price: "$49.00",
        oldPrice: "$65.00",
        discount: "25% OFF",
        image: "/mens/men2.avif",
        hoverImage: "/mens/men3.avif",
        description: "Water-resistant jacket with hood and elastic cuffs.",
        category: "kids",
        tabs: ["latest"],
        colorAvai: ["Yellow", "Blue", "Pink"],
    },
    {
        id: 27,
        name: "Striped Polo Shirt",
        price: "$24.00",
        oldPrice: "$30.00",
        discount: "20% OFF",
        image: "/mens/men2.avif",
        hoverImage: "/productImg/sweatshirt.webp",
        description: "Classic polo shirt with striped detailing.",
        category: "kids",
        tabs: ["weekday"],
        colorAvai: ["White", "Navy"],
    },
    {
        id: 28,
        name: "Relaxed Fit Shorts",
        price: "$31.00",
        image: "/mens/men1.avif",
        hoverImage: "/productImg/onepiece.jpg",
        description: "Soft cotton shorts with elastic waistband.",
        category: "kids",
        tabs: ["streetwear"],
        colorAvai: ["Blue", "Khaki"],
    },
    {
        id: 29,
        name: "Cozy Fleece Set",
        price: "$59.00",
        oldPrice: "$75.00",
        discount: "21% OFF",
        image: "/images/newin3.avif",
        hoverImage: "/productImg/sweatshirt.webp",
        description: "Matching fleece hoodie and jogger set.",
        category: "kids",
        tabs: ["collection"],
        colorAvai: ["Grey", "Pink"],
    },
    {
        id: 30,
        name: "Basic Crewneck Tee",
        price: "$17.00",
        oldPrice: "$22.00",
        discount: "23% OFF",
        image: "/mens/men2.avif",
        hoverImage: "/mens/men3.avif",
        description: "Soft everyday cotton tee for comfort and play.",
        category: "kids",
        tabs: ["latest"],
        colorAvai: ["White", "Light Green"],
    },
];
